import Quiz from '@/components/Quiz'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Quiz App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='container'>
        <div className='row'>
          <div className='col-md-12'>
            <div className='card text-white bg-dark mb-3 shadow border-black rounded'>
              <div className='card-header'>
                <h2>Welcome to Quiz</h2>
              </div>
              <Quiz />
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
